### ISSUE TITLE
Maybe don't override permalink for books

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#20]
The custom field for the amazon URL on books is cool. However there is a drawback. On the /books/ page it displays an excerpt and if the permalink is overwritten, there is no way to read the entire description. I think we should take that field and make a new button perhaps to buy it now or something and allow the single entry to be visited.

**Comment by d4mation** [comment]
Aw, bummer. I liked that Filter :cry:

I agree though. Although I think maybe in that case we should ditch the Custom Field? Its primary purpose was for filtering the Permalink.

Often she has links to things like a Kindle Edition as well as the primary Amazon Link for the hard copy. Maybe a TinyMCE button to allow her to quickly add in stylized Button Links rather than including regular ol' text links?

**Comment by brashrebel** [comment]
Yeah, I like where you're going with this I think. Make it easy to insert buttons and stuff but keep it simpler.

**Comment by d4mation** [comment]
Taking some extra time with this to make it easy to add/remove/rename colors in the future if ever necessary. Had to write my own Localization function since TinyMCE scripts aren't enqueued 🙃 

![image](https://cloud.githubusercontent.com/assets/7770631/19812151/6eeff128-9d02-11e6-85a4-f20e70436e26.png)
