### ISSUE TITLE
Option for alternate color scheme in customizer

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#23]
Not critical and if it is intense, leave it out. But Pat has been a very nice client and is interested in having lots of control over her site. If we could introduce a handful of color schemes that she could select from it would be kind of neat. I think she'd be grateful.

Just a thought.

**Comment by joelworsham** [comment]
Just curious, what is the purpose of Pat being able to change color schemes? Would she want to change the look of her site frequently? I would be concerned with users becoming confused by lack of familiarity.

Or would she just want options to pick one in the end and stick with it? In that case, wouldn't it make sense to just provide some color mock variants and pick one? I guess perhaps I'm just not sure what she wants this for, and there probably is a good reason, but it sounds like a feature of a more do-it-yourself, super-versatile theme, rather than a custom built one. Just trying to wrap my head around this.

**Comment by d4mation** [comment]
I'd have to agree. Setting something up like this is a bit of a headache in itself anyway. SASS lets us manipulate lightness/darkness/saturation/etc natively as we compile the CSS but in the case of this, we would need to have PHP do it on every page load after querying the database for the color values (And implementing custom functions in PHP to do those color transformations).

I think it adds more complications than value unfortunately.

**Comment by joelworsham** [comment]
@brashrebel I'd love to hear your feedback on this. I wasn't completely opposing it, I simply wanted a better understanding of the reasoning.
